# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(max_length=5)),
                ('loser', models.CharField(max_length=5)),
                ('winner_score', models.PositiveIntegerField()),
                ('loser_score', models.PositiveIntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('Football', 'Football')], max_length=100)),
                ('conference', models.CharField(choices=[('PAC_12', 'Pac-12')], max_length=100)),
                ('year', models.IntegerField()),
                ('circle_of_suck', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Season'),
        ),
    ]
