# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20161112_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='sport',
        ),
        migrations.AlterField(
            model_name='season',
            name='conference',
            field=models.CharField(choices=[(b'PAC_12', b'Pac-12'), (b'ACC', b'ACC'), (b'BIG-TEN', b'Big Ten')], max_length=100),
        ),
    ]
