name: Update Data

on:
  push:
    branches:
      - main
  schedule:
    # once a week at midnight on Mondays
    - cron: '0 0 * * MON'

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: data
          path: ./data
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: yarn install
      - name: Update data
        run: yarn update-data
        env:
          CFDB_API_KEY: ${{ secrets.CFDB_API_KEY }}
      - uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: data
          folder: data
