name: Update Data

on:
  push:
    branches:
      - main
  schedule:
    # once a week at midnight on Mondays
    - cron: '0 0 * * MON'

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
          with:
            cmd: install
      - uses: borales/actions-yarn@v2.3.0
          with:
            cmd: update-data
      - uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: data
          folder: data
